### PR TITLE
Episode x tile collisions

### PR DESCRIPTION
**Pull request by SourceR85**

### CODE REVIEW

**Comment by pomle** [comment]
I can't merge this because the merge candidate branch is a WIP which holds my instructions and may be overwritten.

**Comment by SourceR85** [comment]
Ok, then copy the changes manually and reject the request or update the WIP, so that i can contribute to your branch.

**Comment by pomle** [comment]
What branch do you want to merge to? I'm planning the episodes using git commits and I don't think I can keep the script linear with outside contributions to the WIP. :(

**Comment by SourceR85** [comment]
I think, the best i can do is createing a new pull-request to the branch of ep. 4, so that other users can clone a clean code for there study and probably you don't change the code of ep. 4, right?

**Pull request closed without merging**
